#ifndef GCC_EXTERNALPROGRAM_GLOBAL_H
#define GCC_EXTERNALPROGRAM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GCC_EXTERNALPROGRAM_LIBRARY)
#  define GCC_EXTERNALPROGRAM_EXPORT Q_DECL_EXPORT
#else
#  define GCC_EXTERNALPROGRAM_EXPORT Q_DECL_IMPORT
#endif

#endif // GCC_EXTERNALPROGRAM_GLOBAL_H
