######################################################################
# Automatically generated by qmake (2.01a) ? 10 23 12:19:59 2014
######################################################################

TEMPLATE = subdirs

SUBDIRS = \
	netcdf \
	point \
	pointmap \
	polygon \
	polygongroup \
	polyline \
	riversurvey
