#ifndef GD_POLYLINEGROUP_GLOBAL_H
#define GD_POLYLINEGROUP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GD_POLYLINEGROUP_LIBRARY)
#  define GD_POLYLINEGROUP_EXPORT Q_DECL_EXPORT
#else
#  define GD_POLYLINEGROUP_EXPORT Q_DECL_IMPORT
#endif

#endif // GD_POLYLINEGROUP_GLOBAL_H
