#ifndef GCC_RECTANGULARREGIONLONLAT_GLOBAL_H
#define GCC_RECTANGULARREGIONLONLAT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GCC_RECTANGULARREGIONLONLAT_LIBRARY)
#  define GCC_RECTANGULARREGIONLONLAT_EXPORT Q_DECL_EXPORT
#else
#  define GCC_RECTANGULARREGIONLONLAT_EXPORT Q_DECL_IMPORT
#endif

#endif // GCC_RECTANGULARREGIONLONLAT_GLOBAL_H
