#ifndef GD_POINTGROUP_GLOBAL_H
#define GD_POINTGROUP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GD_POINTGROUP_LIBRARY)
#  define GD_POINTGROUP_EXPORT Q_DECL_EXPORT
#else
#  define GD_POINTGROUP_EXPORT Q_DECL_IMPORT
#endif

#endif // GD_POINTGROUP_GLOBAL_H
