version: '{branch}-{build}'

environment:
  CL: /MP
  generator: Visual Studio 16 2019
  ifw_location: C:\Qt\Tools\QtInstallerFramework\4.2
  iric_access_token:
    secure: WDcJrM7sx9jagk006F3OtXqomb90MlJcRIs8LoAyvT0wVzvG+UxeaW+oG9GWb1t8
  kskinoue0612_access_token:
    secure: GzdhhFKWjeLDM22U4ZcrMkAGEEnZLMVbfBR9W8uRQ/LqOtvX2qjPXvC3nvxxWeUc
  scharlton2_access_token:
    secure: CS9f7K3/ePypXUjKJ5S5iX2WFLNpC0IH4LEC9jYXdvcNbaM7CFl0fU5Ws/qUDgvo
  iric_json:
    secure: jtyp65HNtLyMQh9PiY+uEcjGTfpQVZW9OSPpcnug384xLz4tMF4hyEIhPe30DXSpTfpp+UNN6nwsVUUBO7XU+LCWgUsy8jUl7Qz9gl8FhEezCF15Y9HVobbsAxu+qaH37FxZGypHV/I6GJZSiOA3yDatleJQ5/ioJqwa1djx3iPCgfeNoco67lkEzgCrOxlmNtEIOm6kR/43PXUX4FcRBFZb2ZazSsvhgdoax4klrj+4ryv1Hn644T+7M40bUb43QOQeTq5MDNK4nUn3ZjMEQiO4YJAFAsV231FQhiL7EKIW35Xu2N/+PjoZa1Lh9JiCbayEZiIYxBtKrcWdYKdbawxe3EUUvjvDkvFt4KpU1tA7646wUGydR+7ub2+uz2Mn/8TPhvBJzthl8kZZGBjDY22bWLNtN2kTIBPlDYw1v2GxaKtUkmuJ4YB0S/vtOFUvGlvjRd/vg+lOZeUuySHyhNdVNxx387tvD3SVyaPb9+DvWgbHdivzHzMUdc1GPYYNrjqZ6YlFHLgQmttjDw1fofG48PYf61i+GvS99py2v7s75LGuH42eu/TpgdLZnIO4ZZP7BVu/fl9V5j9lV1Coe6OL5OuLZhLB8DMW4VMLFWi7ViGA3bb4PiYUsmtmCsU4fxWL+t0qVF3vW+6qqOsEn/hJTpxYlAT7CmxUPLFRhJQqEB8NXf+0/Kex6uOmdT+buD/WFhK1CL86K/QZufD73zZlkks2MAVfIZReX61AGoky4NDgT3FMRakT7BgQv+GaAgxK+SeQWMMbsxn7ZBey+0D8yvl8V1xhRjAVCDfqv6/O3VW/541P3w4R9NiI69VUwEXHuJ0/m2oDLgRLEEkp3UH0UZCYsb2H7QQ4tgbvhkgZO+t4TbEAuBCiWPmShNSiKGt2KlY+BMGWvi+Acs1vtBa/ytSg5oZKMIvtsaXbyuI9kDBx3R2OezZWE5lOVmJ8DKmF193MhYgUFY+CBF4uCQmwkfj/OsRswRYH4PiGLTZnGzw9TNplfNGGs96K95QVaaE0xaQFYuviV/+/R5lDEygmkyG/XzrXBWU0xr9lWHiIA1YxTrb5fXHVnRxKRZ0u0K6cG5NAtADz4y5fKVTgQsdYXlgdRpzsDeBOet0U42vRaHpTZpvP4f8JBaGTJNKc3DnTHHDid3grl02NuCooKKcIKE09uSQ++6Ov8C9fuNITA1lbbYmhJqOkXMymeacutkdLnc9QAFE0IeeeJffiXYC7GD0jWX2mehtvdmKS0IlnGkUYWMU3NvQ0RWuRylkI2tbs8nOJu3t4bnuix9RmFPZqGIFGv8RN8TG4pGQjp3yKTyzHGqQOioaghqgAcDIOVbIRemmWHssTIdfL877lndDr0EFxfQeJDv93k99ZWEHaLoL3NBDmfoDsOSXW4LxsynyjbV6oXcx1Ya93v6mENaz0czerlY4Gt5EVynWBo5iWZLDR3gEMDN+qw8SFKsX2Hwa5BRI8mU5k7xHq7jOf3aFVpvXiu/GclJ/JW/xT2GeZEux+KeLRmmxOP8SX1B3AqctgCb9L4a4wUv4CyFj3aJvhPh7e8vAohppCkqig+XU25i9JikqcljhWyfQu7DzUpCnk+LATX0aAIJ7EQQQ8uXPTESPszeyoYOcmX2KuPPtL3Bq8MjRv0VIsfIU/ELg7GHYH7Xlu9hwyO5hA5SFHV9jBG2jv6TLbV66BRfHT89LYqm2a/930/lYMl24mvXFBGKzITN1QCn5CgLGVLPKCdd02fGtclGznJ0VfZTPlMIEXLoVZYlZjngNPWBizMERiX2JyfMQsNkgH82kfRtuBRFmMlHoLL8FqJGFPNiqv7IBlK+QBEhJ4iPEmxs3vRRuWoX36vvt+MBJkaeUXJSzR+7toze7DvglWrC+wspXyOMt9dTdEy+NP5PxK+O8R8FI1jgOIOeemIoPQDCivP11ShbKrWUjFBg9qVOaCeDDQ9Dc7U7F3kCWii5IWWv9jgCcexXrQIqWcW6c5QkfG+pvIfaayVgv9j/+MNX8k5PVtzO296D5OPpRzTsd7NOUuvmgzETbAy9HgP0fJdL7hSSHA5tmknPtngeUKRCqhm43yUL3BCbsh7ZmsmPp8xVIOP4eB+gk9u9d7akx1v4RzUEJBVePO5AL0YZEfM5QXefS9gdxapMqZR0d5s0hhe0zNQ7CV0YzEVRW50hAlh/YgG7obnwOOXUy8KzXx0iu3vPKPs7Aqs0jz464ELY7DkZejaOvs8orw6i744jdcbXgOTX94XZnMsbKdy2/bwDqm8RicM9W0NiLnk+evxRZ8G0besXxmtxwmkdSjA7qFW01kjDAmO9aq3W5ofNNbFca0/5p3Fpr1qB5pZ3jPsaXNYd/kNZelczcEvZ/5QQ8bqxjaObWL366PVmi11otRSScev6FbL07QRrZTXaSrO1hC9NKeQnypPJ0VpJOriLOvp9pjcCXP3qdvNp+kydCXTWwDACmpg7ObRNWqbDI466Ldd9NB1cgfNg/l6Fydo6ZG2KLa1NBWdQ4eTm1MKYfcEMI0VJMG99LzF6kAzvdm0Sah4xDJsalyOtRVmjFhF2eeSo1WD3uV2RkWm/z89eHvZ4xJHJqPpeP77k+9EDh/uJUwdcsHYLUJ/qDR+qSL5wXobWGzCpMvg+Fyg0PssIco2KhSK/U2J3kPn2Nk4+zD9PSIpaTre5EJs2Gxkk4bocTRVOAoISmqKfz6S8FqU2Fa3TUAsswnBNy82AKIUu3FqCoh+4Gjsrb9/SQs6E4xP0LRS3wJRrDeu+f2ag9qukG/TaODqcTOFMZVb36Cw/Dr9nUcc4dlS5sbomVQzNvZgKEOg9ZmEXaAhNGJSk7tSLCo1WfURq23UDEoA+SN5ufEp9hWovSk+hTRE1qqiFQOp0Usdu1LjrUKx+sQQBrnJ6Kj2Q4EJE2t5WVmi0r1qfnauzJlW88gQhZwpI3SMbQxOY+AN8qJtHsKffHDscPH2FsKfu1J9Gu3BRkpxhn4m1EsrB70c58bEiqCxbYkz/dwtc8eZCwy65tNKkzvK0wDx05FlYMfbU7aAOSqf1V733d/gWadA9b5wHown1l69ZG8JJvKc02ooTY5uQ==
  scharlton2_json:
    secure: 6Z3JVPecCBbE2xVCpyl6/KE/+GKL4ks7mG3m7nsIHiXPhMFdMge3QNfPoJkTkEe4ysRHqtNG991nQ3eMenlfONS87lXLlcgYTFC5XnbhaAyilySG5TSqwE5t4qER0Qd05/vWYpNCnz8ZHuGzb02DwGDnGg7pW/wNipV26uS2iGCEPyTsdl1Lvwlj9Vn3zlQ0L7fgmopj+WMCtfLpQmOO8TR7hYGZyvrZWpiR4ArwZxVR8sx8edpBFPI5Rd0plRB2FN1zHVh2p38ZW2QeUMTvLUpAKnt9iS8Y4l3ARNyn2OX+JQNNTkzLmiSDJ3HdMrgV734gKFQVy+cwv1wFQ4+qO2c759/o5VRZ/yhWzplcg9EAd92lpthZj0Bowl/xsj03B5/SyZUoWSfHK5gYWfiN2pqP05Fc4QKR7IQ9hos/2nFGz49JfacWD8Uj6YQ6AkgNlLT8UIeVAMYCQQpgduF+FzyohgoHK+VmOaniWcPBQ25aTykD8/SogxMp6+uE59Q8jQWN1uEfDOyKOk45jPZwxQuJEgcU2amqrAFmGi6VXnF37ZMVJCniRfdeK+LWK6hoHyQbi8l7vNx4tKtlDK7am4XBMHaIuIR9WX6vtKo11JWkGRzOMaLHt6wNBiqn0Sf8B7fvKs1QoY27E7cMOKurxzkdkU55+YuF3+rIGsatEjdfAr74AJ38cIvcMBNY52E9Xkc4XuwmaJho/pMEz6ualZ9cUDph1FupJFM4C1Sa4d1qgdSejwyRWJDWxqJJ7PAtoV1qlEnyFIm3xdc2pi3SXh+QqQdlCr9ph1cm+4EQf/GFjPoiryZVQgX8ItxnyThreKwvqqP/oKf5KfKqCqamhWiwMkBWN8ORkWPhcYkbVpmCxRgWsxSwJO23heQXK+h/KEyTPiRDS6F4542eJOPkwCqI8PYvQRRajBN2prQjP3T5YZ6/2jjZcQiP4llk3eezQb7CVfQhmT7oO5OB12F/Uzg1mep6QzXePrktbcDCW7dpcEe0X28ChyeLpGE0+ZyvJvZxedycO2lqJMZhr5hVfY69PPR0gM7Jn2xYowB1XJWVd1TBsA0b07VHK6Gi2mCEKlbOjF2hVKmYHqfu7g4SAv6e2HsUXf9dY/TK2zPpKKOmsxwiKMxcyY4Hw76o4SiMhuODQYYNRF8OLEbSy0RY3ShT0yJKBWnTvD1z14py5aNAjfR2Z7WCP5FgNSwlccBkyeUbxybPkBikR2rJlehONbCLxNVzc1YQo/4BohMZZDXAvYRUFWnWHoX8cGlzIvA69Ck/WJ13BjSu5QVLy8VYcAjySQh61bANNM9beFnVQXaXn5rwIOtncnNSR/O11mMYfGTuuHe2tk4Gz9ASP6lDoyefT+AytYsAiE5Rk8TF2Ax5CH8PNDPttHxmEdg1vGvIpJWPmjiDTzmuxQ7TqugtywmNoDNrnQr0gf15Djd1LD2afGYIUI2GflD5kLvZqWrKBMaV+epuZLnaiHuaSDNcXE6Ke/0p6ycuHBxQe9StFgYl/gqIG6LeiSXTB8vLx3/Zq8oLW9Tt3wE2jR3QuOAORziYAlxbFmAdMY3ROhuMM7uVVy7prh+6Lb+jylZEg91DF6Fwqn8LBOeZrasKb5X7fpZWNvYuX18xFjP1KcN4plHtI1vMEp6FFRyVT901UHpDjWfL37Z97ejMqJvrWZzYw9/uh+zvXQDmhcg0SuORwLJA3nGak1sD1b5Z2HmiJ0LvqwFpgN8OEFHiy7yguRlwYatBFgkuuruUnFoekSHaw5rV8BXG41SfrrWr9THz9JlrA7qHwoDe2AzL1NwlhRGGEEsut70cRZ2uMK6yXVzZSvHCQIuoPa5AEU7eLIdDPmYNTlw4rzFpectadbSo1LzwvC0dNYNdolEIw+LeoADntODLMZhaRggPWkJGvRR2lKxyzEU/Ur/HipgdxcaW7vEIk3YkFfhI1H7n1dHLbrVDvLoHJ5FhkR4h8WL/58Sp994NgCJ1njTjXPFCEX3jfXvww8poHe6qX+hOPteUt9ct7iG4SGdmVhOOxZlXZVNucxa7XulrhlTlH7GNaVcDBbX1IMIYQeqgSylBZ3fEmX2vAElDqLhZ/L3S3kh7m1X3Txz3bDAoUpMeA+rokxI2d5Ur7DHJnjd0LhzgGrsEFGxHY2mvDVdhWwHAZVMrgJZvi1Yv7HjbeXwW+Kjr6NzHYjasc2IUaJNP05qY/mkzhdmpNdVSqmBIa2w0Qo556MkJ3myO+hdrOH36unF2OKq93AzAXAOxdEXw64+Wd9iii5SWdwjfzF1sxoQLVQlEQbMxcXX6jtDw/0pewydaT9gL2Vc/ys/+FJA0opaRDcO9gxW7QLa5kFgcgSq0IcO56DJ/Z/IJClWK2CtKZG5nqrJnZlNvHrSZBJYZWySFRFt7rU8OYirJkuNTusWXTqujw1RukO163YIvDxdI1ttx/qJd64zqJDStDkzPnQs7BSPOaIyfWL7jZJf4NEftyE2tbB8/3lmp62NVqH/IJBIxCkNlxNhlyhB/LwGRHyYD6hyt8123RI2zlsisrXta8X4XuIozmyC0KmG8dRw2vq4ugk/f5sqEzgwBplko2cm9VBXuUuugXKnpBufdh17Qpj0Mr1Yl8eHngHN7ZW28Tzn2TkAiqFsVEDStRCTvx67S+/zQXVWXQy7LsmDKx1MZ2Ap6H9NUJdkL0uh1C6KVhBhov/OWlg0cT4nZbxiDzrHjNNOe3GWFc+KovnaS9wZF8zTWUkmfGsr0xnYVT390PmgpR2n1fpRb2mKibvrJeS2yWWzGhnV/RJ7USVYOCp8vRrHkh0XT4kSqCbMe04oLBWCtaIJ5eTVTHYkramwVw65RbNNDfUitBrWKk7GpskMzwYn+us3+0mbZuFeVXxzabes6BK6mhus9gGSLnsBU0BMXgy7ZEOr91Tm/+fxuqvw5xaafpGMo41MOR8SkJY1DDyjfMVJwn5Ap4AslzcdA6nmE31eUL8w07OovU5IbOamgXiqe7pemESduT5ha68SMLpzaOnx4dn0Ug0pIYE15j7AEBGI3oaySU/BLwAamEye1hR+kZxQ32dBfM8gywhwqK46e2KU9EmN+og==


# Skipping commits affecting specific files (GitHub only).
# also can use [skip appveyor] in message to skip building
skip_commits:
  files:
    - .gitignore
    - README.md
    - manuals/*
    - sdks/*
    - tools/*

image:
  - Visual Studio 2019

# called before clone
# Note that environment variables don't seem to transfer correctly from cmd to ps when
# they contain spaces
init:
  ## Sometimes the plaintext of secure variables is displayed so filter out access_tokens
  - ps: 'Get-ChildItem env: | Where-Object { $_.Name -NotMatch "access_token" }'
  # Only commit and push to master branch or debug-appveyor branch (for testing)
  - ps: $CommitAndPush = (($env:Configuration -eq "Release") -AND (($env:APPVEYOR_REPO_BRANCH -eq "master") -OR ($env:APPVEYOR_REPO_BRANCH -eq "develop_v4")) -AND (!$env:APPVEYOR_PULL_REQUEST_NUMBER))
  - ps: Write-Output $CommitAndPush
  - ps: Write-Output ($env:scharlton2_json).Replace(";", "`r`n") > test.json
  - ps: Select-String auth_provider_x509_cert_url -Path .\test.json
  - ps: Get-FileHash .\test.json
  - ps: throw "finished"

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

# Note mkdir is from Git (C:\Program Files\Git\usr\bin\mkdir.exe)
# It might give unexpected results (use md instead)
before_build:
  - ps: if (! (Test-Path ${env:ifw_location}\bin\repogen.exe)) { throw "repogen.exe not found" }
  - call C:\Qt\5.14.2\msvc2017_64\bin\qtenv2.bat
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd %APPVEYOR_BUILD_FOLDER%
  - curl -L -O https://github.com/i-RIC/iricdev-2019/archive/2019.zip
  - cd \
  - 7z x %APPVEYOR_BUILD_FOLDER%\2019.zip
  - del %APPVEYOR_BUILD_FOLDER%\2019.zip
  - ren c:\iricdev-2019-2019 iricdev-2019
  - cd \iricdev-2019
  - ps: |
      $releases_url = "https://api.github.com/repos/i-RIC/iricdev-2019/releases"
      $latest_response = Invoke-WebRequest -Uri $releases_url/latest -Method GET -UseBasicParsing
      $latest = $latest_response.Content | ConvertFrom-Json
      $url = $latest.assets.browser_download_url
      (New-Object Net.WebClient).DownloadFile($url, "\iricdev-2019\install.7z")
      7z x install.7z
      rm install.7z
  - call create-files.cmd
  - cd %APPVEYOR_BUILD_FOLDER%
  - if not exist libdlls (md libdlls)
  - if not exist libdlls\Debug (md libdlls\Debug)
  - if not exist libdlls\Release (md libdlls\Release)
  - copy /y \iricdev-2019\paths.pri .
  - copy /y \iricdev-2019\dirExt.prop .\tools\data\.
  - ps: 'Get-Command qmake'

build_script:
  - qmake -recursive -tp vc
  - msbuild /nologo /verbosity:minimal /maxCpuCount /target:iricGdPolyline /p:Configuration=%Configuration% src.sln
  - msbuild /nologo /verbosity:minimal /maxCpuCount /p:Configuration=%Configuration% src.sln

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%\tools
  - set SAVE_PATH=%PATH%
  - set PATH=C:\Python37-x64;%PATH%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( python copydllsExt-2019.py )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( python copydllsExt.py )
  - python lrelease.py
  - set PATH=%SAVE_PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: |
      if ($CommitAndPush) {
        mkdir $env:APPVEYOR_BUILD_FOLDER\dist\_build
        Set-Location $env:APPVEYOR_BUILD_FOLDER\dist\_build -ErrorAction Stop
        cmake --version
        Get-Content C:\iricdev-2019\versions.cmd | ForEach-Object {
          if ($_ -match '^set IRICLIB_VER=(.*)$') {
            $env:iriclib_DIR="c:/iricdev-2019/lib/install/iriclib-" + $matches[1] + "/lib/cmake/iriclib"
          }
        }
        cmake -DPREPOST_GUI:PATH=$env:APPVEYOR_BUILD_FOLDER -DSRC_FOLDER:STRING=yasu_src -Diriclib_DIR:PATH=$env:iriclib_DIR -G $env:generator ..
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
      }

artifacts:
#  - path: libdlls\$(Configuration)
#    name: libdlls-$(Configuration)
#  - path: apps\iricgui\$(config)
#    name: iricgui-$(Configuration)

on_success:
  - ps: |
      if ($CommitAndPush) {
        # online_update urls
        $remote_url_iric = "https://github.com/i-RIC/online_update.git"
        $remote_url_scharlton2 = "https://github.com/scharlton2/online_update.git"
        $remote_url_kskinoue0612 = "https://github.com/kskinoue0612/online_update.git"

        $branch = $True
        if ($env:APPVEYOR_REPO_NAME -eq "i-RIC/prepost-gui") {
          $remote_url = $remote_url_iric
          $access_token = $env:iric_access_token
          $branch = $False
        }
        if ($env:APPVEYOR_REPO_NAME -eq "scharlton2/prepost-gui") {
          $remote_url = $remote_url_scharlton2
          # online_update_2020_05_17 expires after a year if not used
          $access_token = $env:scharlton2_access_token
        }
        if ($env:APPVEYOR_REPO_NAME -eq "kskinoue0612/prepost-gui") {
          $remote_url = $remote_url_kskinoue0612
          $access_token = $env:kskinoue0612_access_token
        }

        Set-Location \ -ErrorAction Stop
        git clone -q --branch=master --depth 1 $remote_url online_update 2>&1 | Out-Null
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

        Set-Location .\online_update -ErrorAction Stop

        if ($branch) {
          # create branch when remote is not "i-RIC/prepost-gui"
          git checkout -qb $env:APPVEYOR_JOB_ID
          if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
        }

        # update data\definition.xml and meta\package.xml from yasu_src\packages\gui.prepost

        # set properties
        $v=(Select-String -Path yasu_src\packages\gui.prepost\meta\package.xml -Pattern "(?<=<Version>)(.*)(?=</Version>)").Matches.Value -split "\."
        $v[3] = 1 + $v[3]
        $env:VERSION = $v -join "."
        $tokyo_tz = [System.TimeZoneInfo]::FindSystemTimeZoneById("Tokyo Standard Time")
        $tokyo_date = [System.TimeZoneInfo]::ConvertTimeFromUtc((Get-Date).ToUniversalTime(), $tokyo_tz)
        $env:RELEASE_DATE = $(Get-Date $tokyo_date -Format s).Substring(0,10)
        $env:RELEASE = $env:RELEASE_DATE -replace '-', '.'
        $env:CAPTION = "iRIC GUI " + $v[0] + "." + $v[1] + "." + $v[2]

        # The parentheses around the Get-Content commands below are required
        # to avoid file access errors

        $files=@('yasu_src\packages\gui.prepost\data\definition.xml', `
                'yasu_src\packages\gui.prepost\meta\package.xml')
        foreach ($file in $files) {
          (Get-Content $file) | Foreach-Object {
            $_ -replace "(?<=<Version>)(.*)(?=</Version>)",           "$env:VERSION" `
               -replace "`" version=`"([^`"]*)`"",                    "`" version=`"$env:VERSION`"" `
               -replace "(?<=<ReleaseDate>)(.*)(?=</ReleaseDate>)",   "$env:RELEASE_DATE" `
               -replace "release=`"([^`"]*)`"",                       "release=`"$env:RELEASE`"" `
               -replace "github-sha1=`"([^`"]*)`"",                   "github-sha1=`"$env:APPVEYOR_REPO_COMMIT`""
          } | Set-Content $file
        }

        # distribute files built by prepost-gui
        cmake --build $env:APPVEYOR_BUILD_FOLDER\dist\_build --config release --target install
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

        # read iriclib Version from $in
        # get iriclib ReleaseDate from github releases
        #   see https://docs.github.com/en/rest/reference/releases#get-the-latest-release
        # and write them both to $out
        $in = 'yasu_src\packages\sdk\data\c\lib\cmake\iriclib\iriclibConfigVersion.cmake'
        $outs=@('yasu_src\packages\sdk\meta\package.xml', `
                'yasu_src\packages\miniconda\meta\package.xml')
        $iriclib_ver = (Select-String -Path $in -Pattern '^set\(PACKAGE_VERSION "(?<ver>.*)"\)$').Matches[0].Groups['ver'].Value
        $releases_url="https://api.github.com/repos/i-RIC/iriclib_v4/releases"
        $latest_json = Invoke-WebRequest -Uri $releases_url/latest -Method GET -UseBasicParsing
        $latest = $latest_json.Content | ConvertFrom-Json
        $iriclib_rel = Get-Date $latest.created_at -Format "yyyy-MM-dd"
        # verify versions agree
        if ($latest.tag_name -ne "v$iriclib_ver") {
          throw "iriclib version/release mismatch " + $latest.tag_name  + " -ne " + "v$iriclib_ver"
        }
        foreach ($out in $outs) {
          (Get-Content $out) | Foreach-Object {
            $_ -replace "(?<=<Version>)(.*)(?=</Version>)",           $iriclib_ver `
               -replace "(?<=<ReleaseDate>)(.*)(?=</ReleaseDate>)",   $iriclib_rel
          } | Set-Content $out
        }

        # run repogen to build packages and Updates.xml
        Set-Location \online_update\yasu_src -ErrorAction Stop
        # run repogen
        & ${env:ifw_location}\bin\repogen.exe -p packages --update --include gui.prepost,miniconda,sdk ..\yasu
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

        # run normalize_updatexml.py to normalize Updates.xml.
        Set-Location \online_update -ErrorAction Stop
        py normalize_updatexml.py
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

        # commit and push to https://github.com/i-RIC/online_update.git
        git config --global credential.helper store
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

        # configure git for commit and push
        Add-Content "$HOME\.git-credentials" "https://$($access_token):x-oauth-basic@github.com`n" -ErrorAction Stop
        git config --global user.email "iric.appveyor@gmail.com"
        git config --global user.name "iric.appveyor"
        git config --global core.safecrlf false
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

        # git add -A *.7z *.sha1 *.xml *.dll *.exe *.qm
        git add -A
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

        # Qt dictionaries are now included in gui.runtime package.
        git reset **/qt_*.qm
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

        git commit -m "built by iric.appveyor $env:APPVEYOR_BUILD_VERSION"
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

        if ($branch) {
          git push --set-upstream origin $env:APPVEYOR_JOB_ID 2>&1 | Out-Null
        } else {
          git push --set-upstream origin master 2>&1 | Out-Null
        }
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

        git status
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
      }

on_failure:
  - dir C:\Qt\Tools\QtInstallerFramework
  # the following doesn't work (never finishes):
  # - ps: |
  #     Get-ChildItem -Recurse c:\ | 7z a -si $env:APPVEYOR_BUILD_FOLDER\dir_c.7z
  #     Push-AppveyorArtifact $env:APPVEYOR_BUILD_FOLDER\dir_c.7z
  #     Write-Output "Finished on_failure"
