#ifndef GRAPH2DHYBRID_GLOBAL_H
#define GRAPH2DHYBRID_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAPH2DHYBRID_LIBRARY)
#  define GRAPH2DHYBRID_EXPORT Q_DECL_EXPORT
#else
#  define GRAPH2DHYBRID_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAPH2DHYBRID_GLOBAL_H
