######################################################################
# Automatically generated by qmake (2.01a) ? 10 23 18:49:25 2014
######################################################################

TARGET = iricGraph2dhybrid
TEMPLATE = lib
INCLUDEPATH += ../..

DEFINES += GRAPH2DHYBRID_LIBRARY

include( ../../../paths.pri )

QT += widgets xml

######################
# Internal libraries #
######################

# iricMisc

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../misc/debug"
	} else {
		LIBS += -L"../../misc/release"
	}
}
unix {
	LIBS += -L"../../misc"
}
LIBS += -liricMisc

# iricGuibase

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../guibase/debug"
	} else {
		LIBS += -L"../../guibase/release"
	}
}
unix {
	LIBS += -L"../../guibase"
}
LIBS += -liricGuibase

# iricGuicore

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../guicore/debug"
	} else {
		LIBS += -L"../../guicore/release"
	}
}
unix {
	LIBS += -L"../../guicore"
}
LIBS += -liricGuicore

# iricPostbase

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../postbase/debug"
	} else {
		LIBS += -L"../../postbase/release"
	}
}
unix {
	LIBS += -L"../../postbase"
}
LIBS += -liricPostbase

# iricGraph2d

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../graph2d/debug"
	} else {
		LIBS += -L"../graph2d/release"
	}
}
unix {
	LIBS += -L"../graph2d"
}
LIBS += -liricGraph2d

# iricGdPolyLine

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../geodata/polyline/debug"
	} else {
		LIBS += -L"../../geodata/polyline/release"
	}
}
unix {
	LIBS += -L"../../geodata/polyline"
}
LIBS += -liricGdPolyLine

# iricGdRiversurvey

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../geodata/riversurvey/debug"
	} else {
		LIBS += -L"../../geodata/riversurvey/release"
	}
}
unix {
	LIBS += -L"../../geodata/riversurvey"
}
LIBS += -liricGdRiversurvey

######################
# External libraries #
######################

# Qwt

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -lqwtd
	}
	else {
		LIBS += -lqwt
		DEFINES += QT_NO_DEBUG_OUTPUT
		DEFINES += QT_NO_WARNING_OUTPUT
	}
}
unix {
	LIBS += -lqwt
	DEFINES += QT_NO_DEBUG_OUTPUT
	DEFINES += QT_NO_WARNING_OUTPUT
}

# VTK

LIBS += \
	-lvtkCommonCore-6.1 \
	-lvtkCommonDataModel-6.1 \
	-lvtkCommonExecutionModel-6.1 \
	-lvtkFiltersCore-6.1 \
	-lvtkFiltersExtraction-6.1

# cgnslib
win32 {
	LIBS += -lcgnsdll
}
unix {
	LIBS += -lcgns
}

# Post-Build Event
win32 {
	QMAKE_POST_LINK += copy $(TargetPath) $(SolutionDir)\\libdlls\\$(Configuration)
}

# Input
HEADERS += graph2dhybrid_global.h \
					 graph2dhybridsettingdialog.h \
					 graph2dhybridwindow.h \
					 graph2dhybridwindowactionmanager.h \
					 graph2dhybridwindowcontinuousexportdialog.h \
					 graph2dhybridwindowcontrolwidget.h \
					 graph2dhybridwindowdataitem.h \
					 graph2dhybridwindowdatamodel.h \
					 graph2dhybridwindowdatasourcedialog.h \
					 graph2dhybridwindowlinesettingdialog.h \
					 graph2dhybridwindowobjectbrowser.h \
					 graph2dhybridwindowobjectbrowserview.h \
					 graph2dhybridwindowprojectdataitem.h \
					 graph2dhybridwindowresultsetting.h \
					 graph2dhybridwindowview.h \
					 datamodel/graph2dhybridwindowbaseiterativeresultdataitem.h \
					 datamodel/graph2dhybridwindowdrawsettingdialog.h \
					 datamodel/graph2dhybridwindowgridijkresultdataitem.h \
					 datamodel/graph2dhybridwindowgridpointresultdataitem.h \
					 datamodel/graph2dhybridwindowgridpolylineresultdataitem.h \
					 datamodel/graph2dhybridwindowimportdatadataitem.h \
					 datamodel/graph2dhybridwindowimportdatagroupdataitem.h \
					 datamodel/graph2dhybridwindowresultcopydataitem.h \
					 datamodel/graph2dhybridwindowresultcopygroupdataitem.h \
					 datamodel/graph2dhybridwindowresultdataitem.h \
					 datamodel/graph2dhybridwindowresultgroupdataitem.h \
					 datamodel/graph2dhybridwindowrootdataitem.h \
					 datamodel/graph2dhybridwindowsettingwidget.h
FORMS += graph2dhybridsettingdialog.ui \
				 graph2dhybridwindow.ui \
				 graph2dhybridwindowcontinuousexportdialog.ui \
				 graph2dhybridwindowcontrolwidget.ui \
				 graph2dhybridwindowdatasourcedialog.ui \
				 graph2dhybridwindowlinesettingdialog.ui \
				 datamodel/graph2dhybridwindowdrawsettingdialog.ui \
				 datamodel/graph2dhybridwindowsettingwidget.ui
SOURCES += graph2dhybridsettingdialog.cpp \
					 graph2dhybridwindow.cpp \
					 graph2dhybridwindowactionmanager.cpp \
					 graph2dhybridwindowcontinuousexportdialog.cpp \
					 graph2dhybridwindowcontrolwidget.cpp \
					 graph2dhybridwindowdataitem.cpp \
					 graph2dhybridwindowdatamodel.cpp \
					 graph2dhybridwindowdatasourcedialog.cpp \
					 graph2dhybridwindowlinesettingdialog.cpp \
					 graph2dhybridwindowobjectbrowser.cpp \
					 graph2dhybridwindowobjectbrowserview.cpp \
					 graph2dhybridwindowprojectdataitem.cpp \
					 graph2dhybridwindowresultsetting.cpp \
					 graph2dhybridwindowview.cpp \
					 datamodel/graph2dhybridwindowbaseiterativeresultdataitem.cpp \
					 datamodel/graph2dhybridwindowdrawsettingdialog.cpp \
					 datamodel/graph2dhybridwindowgridijkresultdataitem.cpp \
					 datamodel/graph2dhybridwindowgridpointresultdataitem.cpp \
					 datamodel/graph2dhybridwindowgridpolylineresultdataitem.cpp \
					 datamodel/graph2dhybridwindowimportdatadataitem.cpp \
					 datamodel/graph2dhybridwindowimportdatagroupdataitem.cpp \
					 datamodel/graph2dhybridwindowresultcopydataitem.cpp \
					 datamodel/graph2dhybridwindowresultcopygroupdataitem.cpp \
					 datamodel/graph2dhybridwindowresultdataitem.cpp \
					 datamodel/graph2dhybridwindowresultgroupdataitem.cpp \
					 datamodel/graph2dhybridwindowrootdataitem.cpp \
					 datamodel/graph2dhybridwindowsettingwidget.cpp
TRANSLATIONS += languages/iricGraph2dhybrid_es_ES.ts \
								languages/iricGraph2dhybrid_fr_FR.ts \
								languages/iricGraph2dhybrid_id_ID.ts \
								languages/iricGraph2dhybrid_ja_JP.ts \
								languages/iricGraph2dhybrid_ko_KR.ts \
								languages/iricGraph2dhybrid_ru_RU.ts \
								languages/iricGraph2dhybrid_th_TH.ts \
								languages/iricGraph2dhybrid_vi_VN.ts \
								languages/iricGraph2dhybrid_zh_CN.ts
