#ifndef SOLVERCONSOLE_GLOBAL_H
#define SOLVERCONSOLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SOLVERCONSOLE_LIBRARY)
#  define SOLVERCONSOLEDLL_EXPORT Q_DECL_EXPORT
#else
#  define SOLVERCONSOLEDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // SOLVERCONSOLE_GLOBAL_H
