#ifndef GD_POLYDATAGROUP_GLOBAL_H
#define GD_POLYDATAGROUP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GD_POLYDATAGROUP_LIBRARY)
#  define GD_POLYDATAGROUP_EXPORT Q_DECL_EXPORT
#else
#  define GD_POLYDATAGROUP_EXPORT Q_DECL_IMPORT
#endif

#endif // GD_POLYDATAGROUP_GLOBAL_H
