######################################################################
# Automatically generated by qmake (2.01a) ? 10 23 18:49:25 2014
######################################################################

TARGET = iricPostCrosssection
TEMPLATE = lib
INCLUDEPATH += ../..

DEFINES += POSTCROSSSECTION_LIBRARY

include( ../../../paths.pri )

QT += widgets xml

# Use Precompiled headers (PCH)
PRECOMPILED_HEADER = postcrosssection_pch.h

######################
# Internal libraries #
######################

# iricMisc

unix {
	LIBS += -L"../../misc"
}
LIBS += -liricMisc

# iricGuibase

unix {
	LIBS += -L"../../guibase"
}
LIBS += -liricGuibase

# iricCrosssection

unix {
	LIBS += -L"../../crosssection"
}
LIBS += -liricCrosssection

# iricGuicore

unix {
	LIBS += -L"../../guicore"
}
LIBS += -liricGuicore

# iricPostbase

unix {
	LIBS += -L"../../postbase"
}
LIBS += -liricPostbase

# VTK

LIBS += \
	-lvtkCommonCore-$${VTK_MAJ_MIN}

win32 {
	DESTDIR = $(SolutionDir)/libdlls/$(Configuration)
	LIBS += -L$(SolutionDir)/libdlls/$(Configuration)
}

# Input
HEADERS += postcrosssection_global.h \
           postcrosssectioninternalwindow.h \
           postcrosssectionwindow.h \
           postcrosssectionwindowprojectdataitem.h
SOURCES += postcrosssectioninternalwindow.cpp \
           postcrosssectionwindow.cpp \
           postcrosssectionwindowprojectdataitem.cpp
TRANSLATIONS += languages/iricPostCrosssection_ar_EG.ts \
                languages/iricPostCrosssection_bg_BG.ts \
                languages/iricPostCrosssection_bs_BA.ts \
                languages/iricPostCrosssection_ca_ES.ts \
                languages/iricPostCrosssection_cs_CZ.ts \
                languages/iricPostCrosssection_da_DK.ts \
                languages/iricPostCrosssection_de_DE.ts \
                languages/iricPostCrosssection_el_GR.ts \
                languages/iricPostCrosssection_es_ES.ts \
                languages/iricPostCrosssection_et_EE.ts \
                languages/iricPostCrosssection_eu_ES.ts \
                languages/iricPostCrosssection_fi_FI.ts \
                languages/iricPostCrosssection_fr_FR.ts \
                languages/iricPostCrosssection_gl_ES.ts \
                languages/iricPostCrosssection_hi_IN.ts \
                languages/iricPostCrosssection_hu_HU.ts \
                languages/iricPostCrosssection_id_ID.ts \
                languages/iricPostCrosssection_is_IS.ts \
                languages/iricPostCrosssection_it_IT.ts \
                languages/iricPostCrosssection_ja_JP.ts \
                languages/iricPostCrosssection_ko_KR.ts \
                languages/iricPostCrosssection_ky_KG.ts \
                languages/iricPostCrosssection_lt_LT.ts \
                languages/iricPostCrosssection_lv_LV.ts \
                languages/iricPostCrosssection_nb_NO.ts \
                languages/iricPostCrosssection_nl_NL.ts \
                languages/iricPostCrosssection_pl_PL.ts \
                languages/iricPostCrosssection_pt_BR.ts \
                languages/iricPostCrosssection_pt_PT.ts \
                languages/iricPostCrosssection_ro_RO.ts \
                languages/iricPostCrosssection_ru_RU.ts \
                languages/iricPostCrosssection_sl_SI.ts \
                languages/iricPostCrosssection_sv_SE.ts \
                languages/iricPostCrosssection_th_TH.ts \
                languages/iricPostCrosssection_tr_TR.ts \
                languages/iricPostCrosssection_uk_UA.ts \
                languages/iricPostCrosssection_vi_VN.ts \
                languages/iricPostCrosssection_zh_CN.ts \
                languages/iricPostCrosssection_zh_TW.ts
