#ifndef POSTCROSSSECTION_GLOBAL_H
#define POSTCROSSSECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POSTCROSSSECTION_LIBRARY)
#  define POSTCROSSSECTION_EXPORT Q_DECL_EXPORT
#else
#  define POSTCROSSSECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // POSTCROSSSECTION_GLOBAL_H
