#ifndef GCC_COMPOUNDCHANNEL_GLOBAL_H
#define GCC_COMPOUNDCHANNEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GCC_COMPOUNDCHANNEL_LIBRARY)
#  define GCC_COMPOUNDCHANNEL_EXPORT Q_DECL_EXPORT
#else
#  define GCC_COMPOUNDCHANNEL_EXPORT Q_DECL_IMPORT
#endif

#endif // GCC_COMPOUNDCHANNEL_GLOBAL_H
