#ifndef GRAPH2DVERIFICATION_GLOBAL_H
#define GRAPH2DVERIFICATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAPH2DVERIFICATION_LIBRARY)
#  define GRAPH2DVERIFICATION_EXPORT Q_DECL_EXPORT
#else
#  define GRAPH2DVERIFICATION_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAPH2DVERIFICATION_GLOBAL_H
