######################################################################
# Automatically generated by qmake (2.01a) ? 10 23 18:49:25 2014
######################################################################

TARGET = iricGraph2dVerification
TEMPLATE = lib
INCLUDEPATH += ../..

DEFINES += GRAPH2DVERIFICATION_LIBRARY

include( ../../../paths.pri )

QT += widgets xml

######################
# Internal libraries #
######################

### # iricGui
### 
### win32 {
###         CONFIG(debug, debug|release) {
###                 LIBS += -L"../../gui/debug"
###         } else {
###                 LIBS += -L"../../gui/release"
###         }
### }
### unix {
###         LIBS += -L"../../gui"
### }
### LIBS += -liricGui

# iricMisc

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../misc/debug"
	} else {
		LIBS += -L"../../misc/release"
	}
}
unix {
	LIBS += -L"../../misc"
}
LIBS += -liricMisc

# iricGuibase

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../guibase/debug"
	} else {
		LIBS += -L"../../guibase/release"
	}
}
unix {
	LIBS += -L"../../guibase"
}
LIBS += -liricGuibase

# iricGuicore

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../guicore/debug"
	} else {
		LIBS += -L"../../guicore/release"
	}
}
unix {
	LIBS += -L"../../guicore"
}
LIBS += -liricGuicore

# iricPostbase

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../postbase/debug"
	} else {
		LIBS += -L"../../postbase/release"
	}
}
unix {
	LIBS += -L"../../postbase"
}
LIBS += -liricPostbase

# iricGraph2d

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../graph2d/debug"
	} else {
		LIBS += -L"../graph2d/release"
	}
}
unix {
	LIBS += -L"../graph2d"
}
LIBS += -liricGraph2d

# iricGdPolyLine

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../geodata/polyline/debug"
	} else {
		LIBS += -L"../../geodata/polyline/release"
	}
}
unix {
	LIBS += -L"../../geodata/polyline"
}
LIBS += -liricGdPolyLine

# iricGdRiversurvey

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../geodata/riversurvey/debug"
	} else {
		LIBS += -L"../../geodata/riversurvey/release"
	}
}
unix {
	LIBS += -L"../../geodata/riversurvey"
}
LIBS += -liricGdRiversurvey

######################
# External libraries #
######################

# Qwt

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -lqwtd
	}
	else {
		LIBS += -lqwt
		DEFINES += QT_NO_DEBUG_OUTPUT
		DEFINES += QT_NO_WARNING_OUTPUT
	}
}
unix {
	LIBS += -lqwt
	DEFINES += QT_NO_DEBUG_OUTPUT
	DEFINES += QT_NO_WARNING_OUTPUT
}

# VTK

LIBS += \
	-lvtkCommonCore-6.1 \
	-lvtkCommonDataModel-6.1 \
	-lvtkCommonExecutionModel-6.1 \
	-lvtkFiltersCore-6.1 \
	-lvtkFiltersExtraction-6.1

# cgnslib
win32 {
	LIBS += -lcgnsdll
}
unix {
	LIBS += -lcgns
}

# Post-Build Event
win32 {
	QMAKE_POST_LINK += copy $(TargetPath) $(SolutionDir)\\libdlls\\$(Configuration)
}

# Input
HEADERS += graph2dverification_global.h \
					 graph2dverificationsettingdialog.h \
					 graph2dverificationwindow.h \
					 graph2dverificationwindowactionmanager.h \
					 graph2dverificationwindowcontrolwidget.h \
					 graph2dverificationwindowdataitem.h \
					 graph2dverificationwindowdatamodel.h \
					 graph2dverificationwindowdatasourcedialog.h \
					 graph2dverificationwindowlinesettingdialog.h \
					 graph2dverificationwindowobjectbrowser.h \
					 graph2dverificationwindowobjectbrowserview.h \
					 graph2dverificationwindowprojectdataitem.h \
					 graph2dverificationwindowresultsetting.h \
					 graph2dverificationwindowview.h \
					 graph2dverificationwindowprojectdataitem.h \
					 datamodel/graph2dverificationwindowrootdataitem.h \
    graph2dverificationwindowtopwidget.h
FORMS += graph2dverificationsettingdialog.ui \
				 graph2dverificationwindow.ui \
				 graph2dverificationwindowcontrolwidget.ui \
				 graph2dverificationwindowdatasourcedialog.ui \
				 graph2dverificationwindowlinesettingdialog.ui \
    graph2dverificationwindowtopwidget.ui
SOURCES += graph2dverificationsettingdialog.cpp \
					 graph2dverificationwindow.cpp \
					 graph2dverificationwindowactionmanager.cpp \
					 graph2dverificationwindowcontrolwidget.cpp \
					 graph2dverificationwindowdataitem.cpp \
					 graph2dverificationwindowdatamodel.cpp \
					 graph2dverificationwindowdatasourcedialog.cpp \
					 graph2dverificationwindowlinesettingdialog.cpp \
					 graph2dverificationwindowobjectbrowser.cpp \
					 graph2dverificationwindowobjectbrowserview.cpp \
					 graph2dverificationwindowprojectdataitem.cpp \
					 graph2dverificationwindowresultsetting.cpp \
					 graph2dverificationwindowview.cpp \
					 graph2dverificationwindowprojectdataitem.cpp \
					 datamodel/graph2dverificationwindowrootdataitem.cpp \
    graph2dverificationwindowtopwidget.cpp
TRANSLATIONS += languages/iricGraph2dhybrid_es_ES.ts \
								languages/iricGraph2dhybrid_fr_FR.ts \
								languages/iricGraph2dhybrid_id_ID.ts \
								languages/iricGraph2dhybrid_ja_JP.ts \
								languages/iricGraph2dhybrid_ko_KR.ts \
								languages/iricGraph2dhybrid_ru_RU.ts \
								languages/iricGraph2dhybrid_th_TH.ts \
								languages/iricGraph2dhybrid_vi_VN.ts \
								languages/iricGraph2dhybrid_zh_CN.ts
