#ifndef GCC_CENTERANDWIDTH_GLOBAL_H
#define GCC_CENTERANDWIDTH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GCC_CENTERANDWIDTH_LIBRARY)
#  define GCC_CENTERANDWIDTH_EXPORT Q_DECL_EXPORT
#else
#  define GCC_CENTERANDWIDTH_EXPORT Q_DECL_IMPORT
#endif

#endif // GCC_CENTERANDWIDTH_GLOBAL_H
