#ifndef GCC_GRIDCOMBINE_GLOBAL_H
#define GCC_GRIDCOMBINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GCC_GRIDCOMBINE_LIBRARY)
#  define GCC_GRIDCOMBINE_EXPORT Q_DECL_EXPORT
#else
#  define GCC_GRIDCOMBINE_EXPORT Q_DECL_IMPORT
#endif

#endif // GCC_GRIDCOMBINE_GLOBAL_H
