######################################################################
# Automatically generated by qmake (2.01a) ? 10 23 12:19:59 2014
######################################################################

TEMPLATE = app
TARGET = geometryTest
CONFIG   += console
CONFIG   += c++11

include( ../../paths.pri )

######################
# Internal libraries #
######################

#iricMisc library

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../libs/guibase/debug"
	} else {
		LIBS += -L"../../libs/guibase/release"
	}
}
unix {
	LIBS += -L"../../libs/guibase"
}
LIBS += -liricGuibase

SOURCES += geometry.cpp
