#ifndef GD_POLYGONGROUP_GLOBAL_H
#define GD_POLYGONGROUP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GD_POLYGONGROUP_LIBRARY)
#  define GD_POLYGONGROUP_EXPORT Q_DECL_EXPORT
#else
#  define GD_POLYGONGROUP_EXPORT Q_DECL_IMPORT
#endif

#endif // GD_POLYGONGROUP_GLOBAL_H
