#ifndef POST2DBIRDEYE_GLOBAL_H
#define POST2DBIRDEYE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POST2DBIRDEYE_LIBRARY)
#  define POST2DBIRDEYE_EXPORT Q_DECL_EXPORT
#else
#  define POST2DBIRDEYE_EXPORT Q_DECL_IMPORT
#endif

#endif // POST2DBIRDEYE_GLOBAL_H
