#ifndef RD_RIVERSURVEY_GLOBAL_H
#define RD_RIVERSURVEY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RD_RIVERSURVEY_LIBRARY)
#  define RD_RIVERSURVEY_EXPORT Q_DECL_EXPORT
#else
#  define RD_RIVERSURVEY_EXPORT Q_DECL_IMPORT
#endif

#endif // RD_RIVERSURVEY_GLOBAL_H
