#ifndef DISTANCEMEASURE_API_H
#define DISTANCEMEASURE_API_H

#include <QtCore/QtGlobal>

#if defined(DISTANCEMEASURE_LIBRARY)
#  define DISTANCEMEASURE_API Q_DECL_EXPORT
#else
#  define DISTANCEMEASURE_API Q_DECL_IMPORT
#endif

#endif // DISTANCEMEASURE_API_H
