######################################################################
# Automatically generated by qmake (2.01a) ? 10 23 12:19:59 2014
######################################################################

TEMPLATE = subdirs

SUBDIRS = \
	centerandwidth \
	compoundchannel \
	externalprogram \
	gridcombine \
	gridgenerator \
	laplace \
	poisson \
	rectangularregion \
	rectangularregionlonlat \
	riversurvey \
	riversurvey15d \
	triangle
