######################################################################
# Automatically generated by qmake (2.01a) ? 10 23 12:19:59 2014
######################################################################

TEMPLATE = app
TARGET = iricPythonTest
CONFIG   += console
CONFIG   += c++11

CONFIG(debug, debug|release) {
	QT += gui widgets network
} else {
	QT += gui widgets
}

include( ../../paths.pri )

######################
# Internal libraries #
######################

#iricGui library

unix {
	LIBS += -L"../../libs/gui"
}
LIBS += -liricGui

#iricPython library

unix {
	LIBS += -L"../../libs/iricpython"
}
LIBS += -liricPython

win32 {
	DESTDIR = $(SolutionDir)/libdlls/$(Configuration)
	LIBS += -L$(SolutionDir)/libdlls/$(Configuration)
}

SOURCES += iricpython.cpp
