#ifndef HD_RIVERSURVEYWATERELEVATION_GLOBAL_H
#define HD_RIVERSURVEYWATERELEVATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HD_RIVERSURVEYWATERELEVATION_LIBRARY)
#  define HD_RIVERSURVEYWATERELEVATION_EXPORT Q_DECL_EXPORT
#else
#  define HD_RIVERSURVEYWATERELEVATION_EXPORT Q_DECL_IMPORT
#endif

#endif // HD_RIVERSURVEYWATERELEVATION_GLOBAL_H
