######################################################################
# Automatically generated by qmake (2.01a) ? 10 23 18:49:25 2014
######################################################################

TARGET = iricHdRiversurveywaterelevation
TEMPLATE = lib
INCLUDEPATH += ../..

DEFINES += HD_RIVERSURVEYWATERELEVATION_LIBRARY

include( ../../../paths.pri )

QT += widgets xml

######################
# Internal libraries #
######################

# iricGuicore

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../guicore/debug"
	} else {
		LIBS += -L"../../guicore/release"
	}
}
unix {
	LIBS += -L"../../guicore"
}
LIBS += -liricGuicore

# iricMisc

win32 {
  CONFIG(debug, debug|release) {
    LIBS += -L"../../misc/debug"
  } else {
    LIBS += -L"../../misc/release"
  }
}
unix {
  LIBS += -L"../../misc"
}
LIBS += -liricMisc

# Post-Build Event
win32 {
	QMAKE_POST_LINK += copy $(TargetPath) $(SolutionDir)\\libdlls\\$(Configuration)
}

# Input
HEADERS += hd_riversurveywaterelevation_global.h \
           hydraulicdatariversurveywaterelevation.h \
           hydraulicdatariversurveywaterelevationcreator.h \
           hydraulicdatariversurveywaterelevationimporter.h \
           hydraulicdatariversurveywaterelevationitem.h \
           private/hydraulicdatariversurveywaterelevation_editcaptioncommand.h \
           private/hydraulicdatariversurveywaterelevation_editcolorcommand.h \
           private/hydraulicdatariversurveywaterelevation_edititemcommand.h \
           private/hydraulicdatariversurveywaterelevation_impl.h
SOURCES += hydraulicdatariversurveywaterelevation.cpp \
           hydraulicdatariversurveywaterelevationcreator.cpp \
           hydraulicdatariversurveywaterelevationimporter.cpp \
           hydraulicdatariversurveywaterelevationitem.cpp \
           private/hydraulicdatariversurveywaterelevation_editcaptioncommand.cpp \
           private/hydraulicdatariversurveywaterelevation_editcolorcommand.cpp \
           private/hydraulicdatariversurveywaterelevation_edititemcommand.cpp
RESOURCES += riversurveywaterelevation.qrc
TRANSLATIONS += languages/iricHdRiversurveywaterelevation_es_ES.ts \
                languages/iricHdRiversurveywaterelevation_fr_FR.ts \
                languages/iricHdRiversurveywaterelevation_id_ID.ts \
                languages/iricHdRiversurveywaterelevation_ja_JP.ts \
                languages/iricHdRiversurveywaterelevation_ko_KR.ts \
                languages/iricHdRiversurveywaterelevation_ru_RU.ts \
                languages/iricHdRiversurveywaterelevation_th_TH.ts \
                languages/iricHdRiversurveywaterelevation_vi_VN.ts \
                languages/iricHdRiversurveywaterelevation_zh_CN.ts
