######################################################################
# Automatically generated by qmake (2.01a) ? 10 23 18:49:25 2014
######################################################################

TARGET = iricHdRiversurveywaterelevation
TEMPLATE = lib
INCLUDEPATH += ../..

DEFINES += HD_RIVERSURVEYWATERELEVATION_LIBRARY

include( ../../../paths.pri )

QT += widgets xml

######################
# Internal libraries #
######################

# iricGuicore

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../guicore/debug"
	} else {
		LIBS += -L"../../guicore/release"
	}
}
unix {
	LIBS += -L"../../guicore"
}
LIBS += -liricGuicore

# iricRdRiversurvey

win32 {
	CONFIG(debug, debug|release) {
		LIBS += -L"../../rawdata/riversurvey/debug"
	} else {
		LIBS += -L"../../rawdata/riversurvey/release"
	}
}
unix {
	LIBS += -L"../../rawdata/riversurvey"
}
LIBS += -liricRdRiversurvey

# Input
HEADERS += hd_riversurveywaterelevation_global.h \
           hydraulicdatariversurveywaterelevationimporter.h
SOURCES += hydraulicdatariversurveywaterelevationimporter.cpp
TRANSLATIONS += languages/iricHdRiversurveywaterelevation_es_ES.ts \
                languages/iricHdRiversurveywaterelevation_fr_FR.ts \
                languages/iricHdRiversurveywaterelevation_id_ID.ts \
                languages/iricHdRiversurveywaterelevation_ja_JP.ts \
                languages/iricHdRiversurveywaterelevation_ko_KR.ts \
                languages/iricHdRiversurveywaterelevation_ru_RU.ts \
                languages/iricHdRiversurveywaterelevation_th_TH.ts \
                languages/iricHdRiversurveywaterelevation_vi_VN.ts \
                languages/iricHdRiversurveywaterelevation_zh_CN.ts
