######################################################################
# Automatically generated by qmake (2.01a) ? 10 23 12:19:59 2014
######################################################################

TEMPLATE = subdirs

CONFIG += ordered

SUBDIRS = \
	tmsloader \
	cs \
	geoio \
	misc \
	triangle \
	guibase \
	guicore \
	dataitem \
	geodata \
	gridcreatingcondition \
	hydraulicdata \
	solverconsole \
	postbase \
	post \
	pre \
	gui \
	migui \
	iricpython
