######################################################################
# Automatically generated by qmake (2.01a) ? 10 23 12:19:59 2014
######################################################################

TEMPLATE = subdirs

CONFIG += ordered

SUBDIRS = \
	misc \
	triangle \
	guibase \
	guicore \
	rawdata \
	gridcreatingcondition \
	hydraulicdata \
	solverconsole \
	postbase \
	post \
	pre
