######################################################################
# Automatically generated by qmake (2.01a) ? 10 23 12:19:59 2014
######################################################################

TEMPLATE = subdirs

CONFIG += ordered

SUBDIRS = \
	structured2dgridgdalimporter \
	structured2dgridnayscsvimporter \
	structured2dgridnaysgridimporter \
	structured2dgridvtkimporter \
	unstructured2dgridtriangleimporter \
	unstructured2dgridvtkimporter
