#ifndef GRAPH2DSCATTERED_GLOBAL_H
#define GRAPH2DSCATTERED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAPH2DSCATTERED_LIBRARY)
#  define GRAPH2DSCATTERED_EXPORT Q_DECL_EXPORT
#else
#  define GRAPH2DSCATTERED_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAPH2DSCATTERED_GLOBAL_H
