#ifndef CROSSSECTION_GLOBAL_H
#define CROSSSECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CROSSSECTION_LIBRARY)
#  define CROSSSECTIONDLL_EXPORT Q_DECL_EXPORT
#else
#  define CROSSSECTIONDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // CROSSSECTION_GLOBAL_H
