/* Add C includes here */

#if defined __cplusplus
/* Add C++ includes here */

#include <algorithm>
//#include <cmath>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <vector>

//#include <h5cgnszone.h>
//#include <ogr_spatialref.h>

#include <QAction>
#include <QBrush>
#include <QByteArray>
#include <QColor>
#include <QColorDialog>
#include <QDateTime>
#include <QDialog>
#include <QDomElement>
#include <QDomNode>
#include <QDomNodeList>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QGraphicsItem>
#include <QGraphicsItemGroup>
#include <QIcon>
#include <QInputDialog>
#include <QItemDelegate>
#include <QItemSelection>
#include <QItemSelectionRange>
#include <QLabel>
#include <QList>
#include <QMainWindow>
#include <QMap>
#include <QMenu>
#include <QMessageBox>
#include <QMouseEvent>
#include <QObject>
#include <QPainter>
#include <QPointF>
#include <QPushButton>
#include <QSet>
#include <QSettings>
#include <QSignalMapper>
#include <QStandardItem>
#include <QStandardItemModel>
#include <QString>
#include <QTableWidgetItem>
#include <QtCore/qbytearray.h>
#include <QtCore/qglobal.h>
#include <QtCore/qmetatype.h>
#include <QtCore/QVariant>
#include <QTextStream>
#include <QtGlobal>
#include <QtGui/QIcon>
#include <QtGui/QStandardItemModel>
#include <QTime>
#include <QToolBar>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QVBoxLayout>
#include <QUndoCommand>
#include <QVector2D>
#include <QVector3D>
#include <QXmlStreamWriter>

//#include <shapefil.h>

#include <vtkActor.h>
#include <vtkActor2D.h>
#include <vtkActor2DCollection.h>
#include <vtkActorCollection.h>
#include <vtkAppendPolyData.h>
#include <vtkArrowSource.h>
#include <vtkCamera.h>
#include <vtkCell.h>
#include <vtkCellArray.h>
#include <vtkCellData.h>
#include <vtkCellDataToPointData.h>
#include <vtkCleanPolyData.h>
#include <vtkClipPolyData.h>
#include <vtkColorTransferFunction.h>
#include <vtkConeSource.h>
#include <vtkContourFilter.h>
#include <vtkDataArray.h>
#include <vtkDataSet.h>
#include <vtkDataSetMapper.h>
#include <vtkDiskSource.h>
#include <vtkDoubleArray.h>
#include <vtkExtractCells.h>
#include <vtkExtractGrid.h>
#include <vtkGeometryFilter.h>
#include <vtkGlyph3D.h>
#include <vtkHedgeHog.h>
#include <vtkIdentityTransform.h>
#include <vtkIdList.h>
#include <vtkIntArray.h>
#include <vtkLabeledDataMapper.h>
#include <vtkLegendBoxActor.h>
#include <vtkLine.h>
#include <vtkLineSource.h>
#include <vtkLODActor.h>
#include <vtkLookupTable.h>
#include <vtkMapper.h>
#include <vtkMapperCollection.h>
#include <vtkMaskPoints.h>
#include <vtkPointData.h>
#include <vtkPointLocator.h>
#include <vtkPoints.h>
#include <vtkPolyData.h>
#include <vtkPolyDataMapper.h>
#include <vtkPolyDataMapper2D.h>
#include <vtkPolyDataWriter.h>
#include <vtkPolyLine.h>
#include <vtkProperty.h>
#include <vtkProperty2D.h>
#include <vtkQuad.h>
#include <vtkRenderer.h>
#include <vtkRenderWindow.h>
#include <vtkRungeKutta4.h>
#include <vtkScalarBarActor.h>
#include <vtkScalarBarWidget.h>
#include <vtkScalarsToColors.h>
#include <vtkSmartPointer.h>
#include <vtkStreamTracer.h>
#include <vtkStructuredGrid.h>
#include <vtkStructuredGridGeometryFilter.h>
#include <vtkStructuredGridOutlineFilter.h>
#include <vtkTextActor.h>
#include <vtkTextMapper.h>
#include <vtkTextProperty.h>
#include <vtkTransform.h>
#include <vtkTransformFilter.h>
#include <vtkTriangle.h>
#include <vtkUnstructuredGrid.h>
#include <vtkVertex.h>
#include <vtkWarpVector.h>

#endif // __cplusplus